### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by tyler-kaim1** [design-group/ignition-docker-legacy#68] opened 2023-08-08 16:00 UTC
**Describe the bug**
ignition-docker-mes image is not installing the Sepasoft Modules correctly

**To Reproduce**

1. Create a new docker container using the ignition-docker-mes image
2. Open the designer

**Expected behavior**
The MES Scripts aren't there in the project browser and there are no MES Components in the Component selection

**Screenshots**

**Development Environment (please complete the following information):**

    - OS: Ubuntu
    - Version 20.04.5 LTS

**Additional context**
When I try to add the Vision module to the docker compose file:
`- GATEWAY_MODULES_ENABLED=alarm-notification,allen-bradley-drivers,bacnet-driver,opc-ua,perspective,reporting,tag-historian,web-developer,vision` 
The vision module doesn't show up either.

**Comment by keith-gamble** [comment] 2024-03-18 20:38
Duplicate of #72

**Closed as completed by keith-gamble** 2024-03-18 20:38 UTC
Labels: bug
